import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import { Providers } from "./providers";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Box } from "@chakra-ui/react";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#336aea" />
        <Providers>
          <Navbar />
          <Box as="main" bg="rgba(33, 115, 41, 0.08)">
            {children} <Footer />
          </Box>
        </Providers>
      </body>
    </html>
  );
}
